# Form implementation generated from reading ui file '.\dlg_about.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_about(object):
    def setupUi(self, dlg_about):
        dlg_about.setObjectName("dlg_about")
        dlg_about.resize(748, 442)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlg_about)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(parent=dlg_about)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.lbl_version = QtWidgets.QLabel(parent=dlg_about)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.lbl_version.setFont(font)
        self.lbl_version.setObjectName("lbl_version")
        self.verticalLayout.addWidget(self.lbl_version)
        self.lbl_author = QtWidgets.QLabel(parent=dlg_about)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lbl_author.setFont(font)
        self.lbl_author.setObjectName("lbl_author")
        self.verticalLayout.addWidget(self.lbl_author)
        self.label_4 = QtWidgets.QLabel(parent=dlg_about)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.txt_browser = QtWidgets.QTextBrowser(parent=dlg_about)
        self.txt_browser.setObjectName("txt_browser")
        self.verticalLayout.addWidget(self.txt_browser)
        self.btn_close = QtWidgets.QPushButton(parent=dlg_about)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close)

        self.retranslateUi(dlg_about)
        QtCore.QMetaObject.connectSlotsByName(dlg_about)

    def retranslateUi(self, dlg_about):
        _translate = QtCore.QCoreApplication.translate
        dlg_about.setWindowTitle(_translate("dlg_about", "About Expense Tracker"))
        self.lbl_title.setText(_translate("dlg_about", "Expense Tracker"))
        self.lbl_version.setText(_translate("dlg_about", "Version "))
        self.lbl_author.setText(_translate("dlg_about", "(c) Frank Eisele, 2024"))
        self.label_4.setText(_translate("dlg_about", "Changelog:"))
        self.btn_close.setText(_translate("dlg_about", "Close"))
