# Form implementation generated from reading ui file '.\dlg_account_manager.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_account_manager(object):
    def setupUi(self, dlg_account_manager):
        dlg_account_manager.setObjectName("dlg_account_manager")
        dlg_account_manager.resize(600, 300)
        dlg_account_manager.setMinimumSize(QtCore.QSize(400, 200))
        dlg_account_manager.setMaximumSize(QtCore.QSize(600, 300))
        self.horizontalLayout = QtWidgets.QHBoxLayout(dlg_account_manager)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbl_accounts = QtWidgets.QTableWidget(parent=dlg_account_manager)
        self.tbl_accounts.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tbl_accounts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.tbl_accounts.setObjectName("tbl_accounts")
        self.tbl_accounts.setColumnCount(3)
        self.tbl_accounts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accounts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accounts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_accounts.setHorizontalHeaderItem(2, item)
        self.tbl_accounts.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tbl_accounts)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_add_account = QtWidgets.QPushButton(parent=dlg_account_manager)
        self.btn_add_account.setObjectName("btn_add_account")
        self.verticalLayout.addWidget(self.btn_add_account)
        self.btn_edit_account = QtWidgets.QPushButton(parent=dlg_account_manager)
        self.btn_edit_account.setObjectName("btn_edit_account")
        self.verticalLayout.addWidget(self.btn_edit_account)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_delete_account = QtWidgets.QPushButton(parent=dlg_account_manager)
        self.btn_delete_account.setObjectName("btn_delete_account")
        self.verticalLayout.addWidget(self.btn_delete_account)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btn_close = QtWidgets.QPushButton(parent=dlg_account_manager)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(dlg_account_manager)
        QtCore.QMetaObject.connectSlotsByName(dlg_account_manager)

    def retranslateUi(self, dlg_account_manager):
        _translate = QtCore.QCoreApplication.translate
        dlg_account_manager.setWindowTitle(_translate("dlg_account_manager", "Accounts Manager"))
        item = self.tbl_accounts.horizontalHeaderItem(0)
        item.setText(_translate("dlg_account_manager", "ID"))
        item = self.tbl_accounts.horizontalHeaderItem(1)
        item.setText(_translate("dlg_account_manager", "Account Name"))
        item = self.tbl_accounts.horizontalHeaderItem(2)
        item.setText(_translate("dlg_account_manager", "Account Type"))
        self.btn_add_account.setText(_translate("dlg_account_manager", "Add new account"))
        self.btn_edit_account.setText(_translate("dlg_account_manager", "Edit account"))
        self.btn_delete_account.setText(_translate("dlg_account_manager", "Delete Account"))
        self.btn_close.setText(_translate("dlg_account_manager", "Close"))
