# Form implementation generated from reading ui file '.\dlg_category_manager.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_category_manager(object):
    def setupUi(self, dlg_category_manager):
        dlg_category_manager.setObjectName("dlg_category_manager")
        dlg_category_manager.resize(1092, 555)
        self.horizontalLayout = QtWidgets.QHBoxLayout(dlg_category_manager)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cmb_accounts = QtWidgets.QComboBox(parent=dlg_category_manager)
        self.cmb_accounts.setObjectName("cmb_accounts")
        self.verticalLayout_2.addWidget(self.cmb_accounts)
        self.tbl_categories = QtWidgets.QTableWidget(parent=dlg_category_manager)
        self.tbl_categories.setObjectName("tbl_categories")
        self.tbl_categories.setColumnCount(3)
        self.tbl_categories.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_categories.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_categories.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_categories.setHorizontalHeaderItem(2, item)
        self.tbl_categories.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tbl_categories)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_new = QtWidgets.QPushButton(parent=dlg_category_manager)
        self.btn_new.setObjectName("btn_new")
        self.verticalLayout.addWidget(self.btn_new)
        self.btn_edit = QtWidgets.QPushButton(parent=dlg_category_manager)
        self.btn_edit.setObjectName("btn_edit")
        self.verticalLayout.addWidget(self.btn_edit)
        self.btn_delete = QtWidgets.QPushButton(parent=dlg_category_manager)
        self.btn_delete.setObjectName("btn_delete")
        self.verticalLayout.addWidget(self.btn_delete)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_close = QtWidgets.QPushButton(parent=dlg_category_manager)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(dlg_category_manager)
        QtCore.QMetaObject.connectSlotsByName(dlg_category_manager)

    def retranslateUi(self, dlg_category_manager):
        _translate = QtCore.QCoreApplication.translate
        dlg_category_manager.setWindowTitle(_translate("dlg_category_manager", "Dialog"))
        self.tbl_categories.setSortingEnabled(True)
        item = self.tbl_categories.horizontalHeaderItem(0)
        item.setText(_translate("dlg_category_manager", "Id"))
        item = self.tbl_categories.horizontalHeaderItem(1)
        item.setText(_translate("dlg_category_manager", "Main Category"))
        item = self.tbl_categories.horizontalHeaderItem(2)
        item.setText(_translate("dlg_category_manager", "Sub Category"))
        self.btn_new.setText(_translate("dlg_category_manager", "New"))
        self.btn_edit.setText(_translate("dlg_category_manager", "Edit"))
        self.btn_delete.setText(_translate("dlg_category_manager", "Delete"))
        self.btn_close.setText(_translate("dlg_category_manager", "Close"))
