# Form implementation generated from reading ui file '.\dlg_category_mapping.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_category_mappings(object):
    def setupUi(self, dlg_category_mappings):
        dlg_category_mappings.setObjectName("dlg_category_mappings")
        dlg_category_mappings.resize(929, 474)
        self.horizontalLayout = QtWidgets.QHBoxLayout(dlg_category_mappings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmb_accounts = QtWidgets.QComboBox(parent=dlg_category_mappings)
        self.cmb_accounts.setObjectName("cmb_accounts")
        self.verticalLayout.addWidget(self.cmb_accounts)
        self.tbl_mappings = QtWidgets.QTableWidget(parent=dlg_category_mappings)
        self.tbl_mappings.setObjectName("tbl_mappings")
        self.tbl_mappings.setColumnCount(5)
        self.tbl_mappings.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_mappings.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_mappings.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_mappings.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_mappings.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_mappings.setHorizontalHeaderItem(4, item)
        self.tbl_mappings.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tbl_mappings)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_new = QtWidgets.QPushButton(parent=dlg_category_mappings)
        self.btn_new.setObjectName("btn_new")
        self.verticalLayout_2.addWidget(self.btn_new)
        self.btn_edit = QtWidgets.QPushButton(parent=dlg_category_mappings)
        self.btn_edit.setObjectName("btn_edit")
        self.verticalLayout_2.addWidget(self.btn_edit)
        self.btn_delete = QtWidgets.QPushButton(parent=dlg_category_mappings)
        self.btn_delete.setObjectName("btn_delete")
        self.verticalLayout_2.addWidget(self.btn_delete)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btn_close = QtWidgets.QPushButton(parent=dlg_category_mappings)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout_2.addWidget(self.btn_close)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(dlg_category_mappings)
        QtCore.QMetaObject.connectSlotsByName(dlg_category_mappings)

    def retranslateUi(self, dlg_category_mappings):
        _translate = QtCore.QCoreApplication.translate
        dlg_category_mappings.setWindowTitle(_translate("dlg_category_mappings", "Category Mapping"))
        item = self.tbl_mappings.horizontalHeaderItem(0)
        item.setText(_translate("dlg_category_mappings", "Id"))
        item = self.tbl_mappings.horizontalHeaderItem(1)
        item.setText(_translate("dlg_category_mappings", "Field"))
        item = self.tbl_mappings.horizontalHeaderItem(2)
        item.setText(_translate("dlg_category_mappings", "Value"))
        item = self.tbl_mappings.horizontalHeaderItem(3)
        item.setText(_translate("dlg_category_mappings", "Main Category"))
        item = self.tbl_mappings.horizontalHeaderItem(4)
        item.setText(_translate("dlg_category_mappings", "Sub Category"))
        self.btn_new.setText(_translate("dlg_category_mappings", "Add New Mapping"))
        self.btn_edit.setText(_translate("dlg_category_mappings", "Edit Mapping"))
        self.btn_delete.setText(_translate("dlg_category_mappings", "Delete Mapping"))
        self.btn_close.setText(_translate("dlg_category_mappings", "Close"))
