# Form implementation generated from reading ui file '.\dlg_category_edit.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_category_edit(object):
    def setupUi(self, dlg_category_edit):
        dlg_category_edit.setObjectName("dlg_category_edit")
        dlg_category_edit.resize(529, 114)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(dlg_category_edit)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=dlg_category_edit)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=dlg_category_edit)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.txt_subcategory = QtWidgets.QLineEdit(parent=dlg_category_edit)
        self.txt_subcategory.setObjectName("txt_subcategory")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txt_subcategory)
        self.cmb_maincategory = QtWidgets.QComboBox(parent=dlg_category_edit)
        self.cmb_maincategory.setEditable(True)
        self.cmb_maincategory.setObjectName("cmb_maincategory")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cmb_maincategory)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_save = QtWidgets.QPushButton(parent=dlg_category_edit)
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout_2.addWidget(self.btn_save)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btn_close = QtWidgets.QPushButton(parent=dlg_category_edit)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout_2.addWidget(self.btn_close)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(dlg_category_edit)
        QtCore.QMetaObject.connectSlotsByName(dlg_category_edit)

    def retranslateUi(self, dlg_category_edit):
        _translate = QtCore.QCoreApplication.translate
        dlg_category_edit.setWindowTitle(_translate("dlg_category_edit", "Create or edit category"))
        self.label.setText(_translate("dlg_category_edit", "Main Category"))
        self.label_2.setText(_translate("dlg_category_edit", "Sub Category"))
        self.btn_save.setText(_translate("dlg_category_edit", "Save"))
        self.btn_close.setText(_translate("dlg_category_edit", "Cancel"))
