# Form implementation generated from reading ui file '.\dlg_planned_expenses.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_planned_expenses(object):
    def setupUi(self, dlg_planned_expenses):
        dlg_planned_expenses.setObjectName("dlg_planned_expenses")
        dlg_planned_expenses.resize(908, 587)
        self.horizontalLayout = QtWidgets.QHBoxLayout(dlg_planned_expenses)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmb_accounts = QtWidgets.QComboBox(parent=dlg_planned_expenses)
        self.cmb_accounts.setObjectName("cmb_accounts")
        self.verticalLayout.addWidget(self.cmb_accounts)
        self.tbl_planned_expenses = QtWidgets.QTableWidget(parent=dlg_planned_expenses)
        self.tbl_planned_expenses.setObjectName("tbl_planned_expenses")
        self.tbl_planned_expenses.setColumnCount(4)
        self.tbl_planned_expenses.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_planned_expenses.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_planned_expenses.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_planned_expenses.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_planned_expenses.setHorizontalHeaderItem(3, item)
        self.tbl_planned_expenses.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tbl_planned_expenses)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_new = QtWidgets.QPushButton(parent=dlg_planned_expenses)
        self.btn_new.setObjectName("btn_new")
        self.verticalLayout_2.addWidget(self.btn_new)
        self.btn_edit = QtWidgets.QPushButton(parent=dlg_planned_expenses)
        self.btn_edit.setObjectName("btn_edit")
        self.verticalLayout_2.addWidget(self.btn_edit)
        self.btn_delete = QtWidgets.QPushButton(parent=dlg_planned_expenses)
        self.btn_delete.setObjectName("btn_delete")
        self.verticalLayout_2.addWidget(self.btn_delete)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btn_close = QtWidgets.QPushButton(parent=dlg_planned_expenses)
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout_2.addWidget(self.btn_close)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(dlg_planned_expenses)
        QtCore.QMetaObject.connectSlotsByName(dlg_planned_expenses)

    def retranslateUi(self, dlg_planned_expenses):
        _translate = QtCore.QCoreApplication.translate
        dlg_planned_expenses.setWindowTitle(_translate("dlg_planned_expenses", "Planned Expenses"))
        item = self.tbl_planned_expenses.horizontalHeaderItem(0)
        item.setText(_translate("dlg_planned_expenses", "Id"))
        item = self.tbl_planned_expenses.horizontalHeaderItem(1)
        item.setText(_translate("dlg_planned_expenses", "Name"))
        item = self.tbl_planned_expenses.horizontalHeaderItem(2)
        item.setText(_translate("dlg_planned_expenses", "Main Category"))
        item = self.tbl_planned_expenses.horizontalHeaderItem(3)
        item.setText(_translate("dlg_planned_expenses", "Sub Category"))
        self.btn_new.setText(_translate("dlg_planned_expenses", "New Planned Expense"))
        self.btn_edit.setText(_translate("dlg_planned_expenses", "Edit"))
        self.btn_delete.setText(_translate("dlg_planned_expenses", "Delete"))
        self.btn_close.setText(_translate("dlg_planned_expenses", "Close"))
